<a href="https://colab.research.google.com/github/ammulu-rgb/G.Hema-latha/blob/main/G_Hema_latha_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================
# FACTORY PRODUCTION PLANNER (A7)
# Cell 1: Imports
# ============================================

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

from IPython.display import display, Markdown

In [ ]:
# ============================================
# Cell 2: INPUT CONFIGURATION
# ============================================

# Products
products = ["Product A", "Product B", "Product C"]

# Machines
machines = ["Machine 1", "Machine 2", "Machine 3"]

# ------------------------------------------------
# Time required by each product on each machine
#
# Rows    -> machines
# Columns -> products
#
# Example:
# Machine 1: A needs 2 hours, B needs 1 hour, C needs 1 hour
# ------------------------------------------------

time_required = np.array([
    [2, 1, 1],   # Machine 1
    [1, 2, 1],   # Machine 2
    [1, 1, 2]    # Machine 3
], dtype=float)

# Available hours for each machine
machine_capacity = np.array([
    100,   # Machine 1
    100,   # Machine 2
    100    # Machine 3
], dtype=float)

# Optional target production.
#
# If None:
#     We solve the machine-capacity equations directly:
#         A*x = capacity
#
# If you provide a target workload/capacity, the same
# mathematical system is used.
#
# Here we use machine capacities as the right-hand side.
target = machine_capacity.copy()

print("Products:", products)
print("Machines:", machines)
print("\nTime requirement matrix:")
print(time_required)

print("\nMachine capacities:")
for machine, capacity in zip(machines, machine_capacity):
    print(f"{machine}: {capacity} hours")

Products: ['Product A', 'Product B', 'Product C']
Machines: ['Machine 1', 'Machine 2', 'Machine 3']

Time requirement matrix:
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]

Machine capacities:
Machine 1: 100.0 hours
Machine 2: 100.0 hours
Machine 3: 100.0 hours
